tunnel: a53ca783-fbc3-4ad3-bdb5-7d3ca92188ac
credentials-file: /root/.cloudflared/a53ca783-fbc3-4ad3-bdb5-7d3ca92188ac.json

ingress:
  - hostname: db.tudominio.com
    service: tcp://localhost:5432
  - service: http_status:404 