steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pros-app:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pros-app:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
    - 'run'
    - 'deploy'
    - 'pros-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/pros-app:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NODE_ENV=production,DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_PORT=${_DB_PORT},DB_SSL=true'

images:
  - 'gcr.io/$PROJECT_ID/pros-app:$COMMIT_SHA'

substitutions:
  _DB_HOST: '34.42.197.64'
  _DB_NAME: 'railway'
  _DB_USER: 'postgres'
  _DB_PASSWORD: 'LZAfBQzBxEJvBkHMzCMXbCKFZpxEqLqC'
  _DB_PORT: '5432'
  _PROJECT_ID: 'inner-root-463214-j1' 